---
title: "NBA_Shots"
output: html_document
date: "2023-04-13"
---

# Packages
```{r}
# ------------------------- If you do not have the packages loaded, remove the hastag and run the line to install.

#install.packages("tidyverse")
library(tidyverse)

#install.packages("dplyr")
library(dplyr)

#install.packages("ggplot2")
library(ggplot2)
```

# Court Plotting Function (Run All at Once)
```{r}
# ------------------------- Creating Court and Plotting
circle_points = function(center = c(0, 0), radius = 1, npoints = 360) {
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame(x = center[1] + radius * cos(angles),
                    y = center[2] + radius * sin(angles)))
}

width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14

court_themes = list(
  light = list(
    court = 'floralwhite',
    lines = 'black',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = "#000000"
  ),
  dark = list(
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "#000000"
  ),
  ppt = list(
    court = 'gray15',
    lines = 'white',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray15"
),
  white = list(
    court = 'white',
    lines = 'black',
    text = 'black',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = "gray15"
)
)


plot_court = function(court_theme = court_themes$light, use_short_three = FALSE) {
  if (use_short_three) {
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = "perimeter"
  )
  
  court_points = bind_rows(court_points , data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = "outer_key"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = "backboard"
  ))
  
  court_points = bind_rows(court_points , data_frame(
    x = c(0, 0), y = c(backboard_offset, backboard_offset + neck_length), desc = "neck"
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = "foul_circle_top")
  
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0("foul_circle_bottom_", angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x, y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = "three_point_line"
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  
  court_points <- court_points
  
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines, sizes = 2
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray15', color = 'gray15'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = "lines"),
      legend.position = "bottom",
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1.0))
    )
}
```

# Data & Plotting (Single Game for a Player)
```{r}
# ------------------------- Load the Dataset

shots_data <- read_csv("NBA_2004_2023_Shots.csv")


# ------------------------- Filter for Single Game Shots by Date & Player Name

shots <- shots_data %>% 
  filter(GAME_DATE == "04-04-2023") %>%
  filter(PLAYER_NAME == "Joel Embiid" )


# ------------------------- Create Plot

plot_court(court_themes$white, use_short_three = F) +
  # ---- plot shot "points" with x & y locations
  geom_point(data = shots, aes(x = LOC_X, y = LOC_Y, color = SHOT_MADE, fill = SHOT_MADE), 
             size =3, shape = 21, stroke = .5) +
  # ---- plot player hedashot (remove these 2 lines if you're plotting multiple players!)
  draw_image(paste0("https://cdn.nba.com/headshots/nba/latest/1040x760/", unique(shots$PLAYER_ID), ".png"), 
             x = -19, y = -1.3, width = 9, height = 9) +
  # ---- plot team logo (remove these 2 lines if you're plotting multiple teams!)
  draw_image(paste0("https://cdn.nba.com/logos/nba/", unique(shots$TEAM_ID), "/primary/L/logo.svg"), 
             x = 12, y = 0.2, width = 6, height = 6) +
  # ---- fill the points with color
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", breaks = c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","red2"), aesthetics = "fill", breaks = c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  # ----
  scale_x_continuous(limits = c(-27.5, 27.5)) +
  scale_y_continuous(limits = c(0, 45)) +
  # ---- Add title and subtitle (manual!)
  labs(
    title = "Joel Embiid - Shot Chart",
    subtitle = "April 4th, 2023 vs. Boston Celtics"
  ) +
  # ----
  annotate(geom = 'text', x = 0, y = 2, hjust = .5, 
        label = "Tutorial: @DSamangy", size = 2, color = "black", face = "bold") +
  # ---- Theme options for manipulating the look of the plot
  theme(
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 7, face = "bold", colour = "black"),
        legend.background = element_rect(fill = "white", colour = "white"),
        legend.box.background = element_rect(fill = "white", colour = "white"),
        legend.key = element_rect(fill = "white", colour = "white"),
        legend.margin = margin(t = -.5, unit='cm'),
        legend.box.margin=margin(-15,0,15,0),
        #
        plot.background = element_rect(fill="white", color = "white"),
        panel.background = element_rect(fill="white", color = "white"),
        #
        plot.title = element_text(hjust = 0.5, size = 22, vjust = -9, face = "bold", colour = "black"),
        plot.subtitle = element_text(hjust = 0.5, size = 12, vjust = -15, face = "bold", colour = "black"), 
        plot.margin = margin(0, 0, .5, 0, "cm"),
        ) 



# ------------------------- Save Plot

ggsave("Player_Shot_Chart.png", height = 6, width = 6, dpi = "retina")
```

# Data & Plotting (Single Game for a Team)
```{r}
# ------------------------- Load the Dataset

shots_data <- read_csv("NBA_2004_2023_Shots.csv")


# ------------------------- Filter for Single Game Shots by Date & Team Name

shots <- shots_data %>% 
  filter(GAME_DATE == "04-04-2023") %>%
  filter(TEAM_NAME == "Philadelphia 76ers")


# ------------------------- Create Plot

plot_court(court_themes$white, use_short_three = F) +
  # ---- plot shot "points" with x & y locations
  geom_point(data = shots, aes(x = LOC_X, y = LOC_Y, color = SHOT_MADE, fill = SHOT_MADE), 
             size =3, shape = 21, stroke = .5)  +
  # ---- plot team logo on left (remove these 2 lines if you're plotting multiple teams!)
  draw_image(paste0("https://cdn.nba.com/logos/nba/", unique(shots$TEAM_ID), "/primary/L/logo.svg"), 
             x = -18, y = 0.2, width = 6, height = 6)  +
  # ---- plot team logo on right (remove these 2 lines if you're plotting multiple teams!)
  draw_image(paste0("https://cdn.nba.com/logos/nba/", unique(shots$TEAM_ID), "/primary/L/logo.svg"), 
             x = 12, y = 0.2, width = 6, height = 6) +
  # ---- fill the points with color
  scale_color_manual(values = c("green4","red3"), aesthetics = "color", breaks = c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  scale_fill_manual(values = c("green2","red2"), aesthetics = "fill", breaks = c("TRUE", "FALSE"), labels=c("Made", "Missed")) +
  # ----
  scale_x_continuous(limits = c(-27.5, 27.5)) +
  scale_y_continuous(limits = c(0, 45)) +
  # ---- Add title and subtitle (manual!)
  labs(
    title = "Philadelphia 76ers - Shot Chart",
    subtitle = "April 4th, 2023 vs. Boston Celtics"
  ) +
  # ----
  annotate(geom = 'text', x = 0, y = 2, hjust = .5, 
        label = "Tutorial: @DSamangy", size = 2, color = "black", face = "bold") +
  # ---- Theme options for manipulating the look of the plot
  theme(
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.text = element_text(hjust = .5, size = 7, face = "bold", colour = "black"),
        legend.background = element_rect(fill = "white", colour = "white"),
        legend.box.background = element_rect(fill = "white", colour = "white"),
        legend.key = element_rect(fill = "white", colour = "white"),
        legend.margin = margin(t = -.5, unit='cm'),
        legend.box.margin=margin(-15,0,15,0),
        #
        plot.background = element_rect(fill="white", color = "white"),
        panel.background = element_rect(fill="white", color = "white"),
        #
        plot.title = element_text(hjust = 0.5, size = 22, vjust = -9, face = "bold", colour = "black"),
        plot.subtitle = element_text(hjust = 0.5, size = 12, vjust = -15, face = "bold", colour = "black"), 
        plot.margin = margin(0, 0, .5, 0, "cm"),
        ) 



# ------------------------- Save Plot

ggsave("Team_Shot_Chart.png", height = 6, width = 6, dpi = "retina")
```

